"""Generate RCK's C# registration tables from the CCU interface spec in docs/ccu-interface.json.

Only identifiers and formats come from the spec (names, display names, costs,
appearance roll values). Descriptions and behaviour are written by hand in the
system modules.

The plugin's own identity (GUID, name, version) is hand-written in RCK/Core/Plugin.cs, not taken from the spec.
Display names keep the spec's format with RCK's tag in place of CCU's ("[CCU] Group - Name" -> "[RCK] Group - Name").

Usage: python tools/ccu-codegen/gen_traits_cs.py [--spec docs/ccu-interface.json] [--out RCK/Core/Generated]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def cs(s: str | None) -> str:
    if s is None:
        return "null"
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "") + '"'


def cs_arr(xs) -> str:
    xs = [x for x in (xs or []) if isinstance(x, str)]
    if not xs:
        return "Empty"
    return "new[] { " + ", ".join(cs(x) for x in xs) + " }"


def num(v, default=0) -> int:
    return v if isinstance(v, int) and not isinstance(v, bool) else default


def avail_cc(v) -> str:
    if v is True:
        return "RckAvailability.Always"
    if isinstance(v, dict) and "designerEdition" in v.get("expr", ""):
        return "RckAvailability.DesignerEdition"
    return "RckAvailability.Never"


def display(s: str | None) -> str | None:
    """CCU's display tag becomes RCK's; the rest of the display format is unchanged."""
    if s is None:
        return None
    for old, new in (("[CCU+]", "[RCK+]"), ("[CCU]", "[RCK]")):
        if s.startswith(old):
            return new + s[len(old):]
    return s


def bases(xs) -> list[str]:
    """CCU's class chain without its universal root (T_CCU / M_CCU), which every trait shares."""
    return [x for x in (xs or []) if isinstance(x, str) and not x.endswith("_CCU")]


def folder(path: str) -> str:
    """'CCU/Systems/Hiring/Designer Traits/Hire Type/X.cs' -> 'Hiring/Hire Type'."""
    parts = [p for p in path.split("/")[1:-1] if p not in ("Systems", "Traits", "Designer Traits")]
    return "/".join(p for i, p in enumerate(parts) if not (p == "Player Traits" and i > 0))


def write(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(text.replace("\r\n", "\n").replace("\n", "\r\n").encode("utf-8"))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--spec", default=str(ROOT / "docs" / "ccu-interface.json"))
    ap.add_argument("--out", default=str(ROOT / "RCK" / "Core" / "Generated"))
    a = ap.parse_args()
    spec = json.loads(Path(a.spec).read_text(encoding="utf-8"))
    out = Path(a.out)

    hdr = ("// <auto-generated>\n// Generated by tools/ccu-codegen/gen_traits_cs.py from docs/ccu-interface.json.\n"
           "// Do not edit by hand.\n// </auto-generated>\n")

    classes, rows = [], []
    for tid, t in sorted(spec["traits"].items(), key=lambda kv: kv[0].lower()):
        u = t.get("unlock") or {}
        inner = u.get("Unlock") or {}
        kind = "RckTraitKind.Player" if t["kind"] == "player" else "RckTraitKind.Designer"
        ns = (t.get("namespace") or "").split(".")
        group = ns[-1] if ns else ""
        classes.append(f"    public sealed class {tid} : RckTrait {{ }}")
        cancels = [c for c in list(u.get("Cancellations") or []) + list(inner.get("cancellations") or [])
                   if isinstance(c, str)]
        upgrade = u.get("Upgrade") if isinstance(u.get("Upgrade"), str) else inner.get("upgrade")
        rows.append(
            f"            new RckTraitInfo(typeof(T.{tid}), {cs(tid)}, {kind}, {cs(group)}, {cs(folder(t['path']))}, "
            f"{cs(display(t.get('display_en')))}, {'true' if t['in_head'] else 'false'}, {cs(t['versions'][0])}, "
            f"{num(u.get('CharacterCreationCost'))}, {num(u.get('UnlockCost'))}, "
            f"{avail_cc(u.get('IsAvailableInCC'))}, {'true' if u.get('IsAvailable') is True else 'false'}, "
            f"{'true' if inner.get('cantLose') is True else 'false'}, {'true' if inner.get('cantSwap') is True else 'false'}, "
            f"{cs(upgrade if isinstance(upgrade, str) else None)}, "
            f"{cs_arr(cancels)}, {cs_arr(t.get('rolls'))}, {cs_arr(bases(t.get('bases')))}),")

    write(out / "TraitTypes.g.cs", hdr + "namespace RCK.TraitTypes\n{\n"
          "    // One type per trait ID: RogueLibs derives a custom trait's ID from its type name.\n"
          + "\n".join(classes) + "\n}\n")

    legacy = spec.get("legacy", {})
    conv_rows = [f"            {{ {cs(k)}, {cs_arr(v)} }},"
                 for k, v in sorted(legacy.get("TraitConversions", {}).items())]
    mut_conv = {**legacy.get("MutatorConversions", {}), **legacy.get("ChallengeConversions", {})}
    mconv_rows = [f"            {{ {cs(k)}, {cs_arr(v)} }}," for k, v in sorted(mut_conv.items())]
    goal_rows = [f"            new RckGoalInfo({cs(g)}, {cs(v.get('const'))}, {cs_arr(v.get('lists'))}),"
                 for g, v in sorted(spec["goals"].items())]

    def named(section, extension=False):
        return [f"            new RckNamedInfo({cs(k)}, {cs(display(v.get('display_en')))}, {'true' if v['in_head'] else 'false'}"
                + (f", {cs(v.get('description_en'))}" if extension else "") + "),"
                for k, v in sorted(spec[section].items())
                if not k.startswith("<dynamic:") and bool(v.get("extension")) == extension]

    muts, items, effects = named("mutators"), named("items"), named("effects")
    ext_muts = named("mutators", extension=True)
    objs = spec.get("object_lists", {})
    factions = (spec.get("extensions") or {}).get("factions") or {}
    recruit = factions.get("recruit") or {}

    def objlist(name):
        return cs_arr((objs.get(name) or {}).get("objects"))

    nl = "\n"
    write(out / "RckData.g.cs", hdr + f"""using System.Collections.Generic;
using T = RCK.TraitTypes;

namespace RCK
{{
    public static partial class RckData
    {{
        private static readonly string[] Empty = new string[0];

        public static readonly RckTraitInfo[] Traits =
        {{
{nl.join(rows)}
        }};

        /// <summary>Legacy trait ID (from older CCU versions) -> current trait IDs.</summary>
        public static readonly Dictionary<string, string[]> TraitConversions = new Dictionary<string, string[]>
        {{
{nl.join(conv_rows)}
        }};

        /// <summary>Legacy mutator/challenge name (from older CCU versions) -> current names.</summary>
        public static readonly Dictionary<string, string[]> MutatorConversions = new Dictionary<string, string[]>
        {{
{nl.join(mconv_rows)}
        }};

        public static readonly RckGoalInfo[] Goals =
        {{
{nl.join(goal_rows)}
        }};

        public static readonly RckNamedInfo[] Mutators =
        {{
{nl.join(muts)}
        }};

        /// <summary>RCK's own mutators (<c>RCK_</c> IDs), which CCU content never uses.</summary>
        public static readonly RckNamedInfo[] ExtensionMutators =
        {{
{nl.join(ext_muts)}
        }};

        public static readonly RckNamedInfo[] Items =
        {{
{nl.join(items)}
        }};

        public static readonly RckNamedInfo[] Effects =
        {{
{nl.join(effects)}
        }};

        public static readonly string[] InvestigateableObjects = {objlist('InvestigateableObjects_Slot1')};
        public static readonly string[] ContainerObjects = {objlist('ContainerObjects_Slot1')};
        public static readonly string[] FireParticleObjects = {objlist('FireParticleEffectObjects')};

        /// <summary>Faction keys (an RCK addition): a faction's traits are <c>&lt;key&gt;_&lt;grade&gt;</c>.</summary>
        public static readonly string[] FactionKeys = {cs_arr(factions.get('keys'))};
        public static readonly string[] FactionGrades = {cs_arr(list(factions.get('grades') or []))};
        /// <summary>Player-trait suffix for faction membership only: <c>&lt;key&gt;_&lt;suffix&gt;</c>.</summary>
        public const string FactionMemberSuffix = {cs(factions.get('member'))};
        /// <summary>Mutator prefix for a level or campaign faction relationship matrix.</summary>
        public const string FactionMatrixPrefix = {cs((factions.get('matrix') or {}).get('prefix'))};
        /// <summary>Older spellings of <see cref="FactionMatrixPrefix"/>, still read (see <see cref="LegacyCcu"/>).</summary>
        public static readonly string[] FactionMatrixLegacyPrefixes = {cs_arr((factions.get('matrix') or {}).get('legacy_prefixes'))};
        /// <summary>Mutator prefix for per-faction recruit policies.</summary>
        public const string FactionRecruitPrefix = {cs((recruit.get('matrix') or {}).get('prefix'))};
    }}
}}
""")
    print(f"traits={len(rows)} goals={len(goal_rows)} mutators={len(muts)}+{len(ext_muts)} items={len(items)} effects={len(effects)}"
          f" trait_conversions={len(conv_rows)} -> {out}")


if __name__ == "__main__":
    main()
