"""Generate RCK/Core/Generated/TraitDescriptions.g.cs from RCK/Core/Data/trait-descriptions.json.

The JSON holds one English character-creator description per trait id, written for RCK from what each trait does
(never copied from CCU; tools/clean-room/check_overlap.py checks that). Entries marked "dynamic" get their final
text from a module at runtime; the table still gives them a default.

Usage: python tools/ccu-codegen/gen_descriptions_cs.py [--json RCK/Core/Data/trait-descriptions.json] [--out RCK/Core/Generated]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def cs(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "") + '"'


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", default=str(ROOT / "RCK" / "Core" / "Data" / "trait-descriptions.json"))
    ap.add_argument("--out", default=str(ROOT / "RCK" / "Core" / "Generated"))
    args = ap.parse_args()

    rows = json.loads(Path(args.json).read_text(encoding="utf-8-sig"))
    ids = [r["id"] for r in rows]
    if ids != sorted(ids) or len(set(ids)) != len(ids):
        raise SystemExit("trait-descriptions.json must be sorted by id with no duplicates")
    for r in rows:
        if not isinstance(r.get("en"), str) or not r["en"].strip():
            raise SystemExit(f"{r['id']}: empty description")

    lines = [
        "// <auto-generated>",
        "// Generated by tools/ccu-codegen/gen_descriptions_cs.py from RCK/Core/Data/trait-descriptions.json.",
        "// Do not edit by hand.",
        "// </auto-generated>",
        "#nullable enable",
        "using System;",
        "using System.Collections.Generic;",
        "",
        "namespace RCK",
        "{",
        "    /// <summary>The English character-creator description of every RCK trait.</summary>",
        "    public static class TraitDescriptions",
        "    {",
        f"        private static readonly Dictionary<string, string> table = new Dictionary<string, string>({len(rows)}, StringComparer.Ordinal)",
        "        {",
    ]
    lines += [f"            [{cs(r['id'])}] = {cs(r['en'])}," for r in rows]
    lines += [
        "        };",
        "",
        "        private static readonly HashSet<string> dynamic = new HashSet<string>(StringComparer.Ordinal)",
        "        {",
    ]
    lines += [f"            {cs(r['id'])}," for r in rows if r.get("dynamic")]
    lines += [
        "        };",
        "",
        "        /// <summary>The number of described traits.</summary>",
        "        public static int Count => table.Count;",
        "",
        "        /// <summary>The trait's description, or null if the table has none.</summary>",
        "        public static string? Get(string traitId) => table.TryGetValue(traitId, out string text) ? text : null;",
        "",
        "        /// <summary>True if a module sets this trait's final description at runtime.</summary>",
        "        public static bool IsDynamic(string traitId) => dynamic.Contains(traitId);",
        "    }",
        "}",
        "",
    ]
    out = Path(args.out) / "TraitDescriptions.g.cs"
    out.write_bytes("\r\n".join(lines).encode("utf-8"))
    print(f"wrote {out.relative_to(ROOT) if out.is_relative_to(ROOT) else out}: {len(rows)} descriptions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
