<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>RCK.Social</AssemblyName>
    <RootNamespace>RCK.Social</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Remove="RCK" />
    <Reference Include="RCK"><HintPath>..\..\Core\obj\$(Configuration)\RCK.dll</HintPath><Private>False</Private></Reference>
  </ItemGroup>

</Project>
